### ISSUE TITLE
I'm sorry, but where is the implementation of the proposed RPC network?

### ISSUE THREAD

**Issue by machengcheng2016** [jiawei-ren/modelnetc#2]
Greetings!
Really solid work. However, I cannot find codes about the RPC network as presented in Section 6. Do I miss it?

**Comment by jiawei-ren** [comment]
Thanks for your interest. Implementation of RPC can be found in [PCT/model.py](https://github.com/jiawei-ren/ModelNet-C/blob/main/PCT/model.py#L27).

**Comment by machengcheng2016** [comment]
Ok, thx.
