### ISSUE TITLE
I am curious about pretrain dataset of pointbert 

### ISSUE THREAD

**Issue by Dali936** [jiawei-ren/modelnetc#3]
![image](https://github.com/user-attachments/assets/9390de10-4db9-42e9-b539-4143dc2e2522)
Hi,i want to know if the pretrain dataset of pointbert is shapenet

**Comment by auniquesun** [comment]
> ![image](https://private-user-images.githubusercontent.com/83868746/356563980-9390de10-4db9-42e9-b539-4143dc2e2522.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQzOTc0MjksIm5iZiI6MTcyNDM5NzEyOSwicGF0aCI6Ii84Mzg2ODc0Ni8zNTY1NjM5ODAtOTM5MGRlMTAtNGRiOS00MmU5LWI1MzktNDE0M2RjMmUyNTIyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIzVDA3MTIwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ5ZDhmMTZkMDNkZWRhYjRhMDBmOWI4NDVjZjQ0ZmJkNWUxNGJlZDI4MDc1N2UzNGNlZTUxYTVhZGMzOTQ0YWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.K2UCsGtkQqHUMm9lTzA0TpB7s9LErLfyQYTMiAwxAxM) Hi,i want to know if the pretrain dataset of pointbert is shapenet

According to the pointbert paper, the pre-training dataset is shapenet, so what's the consequence?

**Comment by Dali936** [comment]
> > ![image](https://private-user-images.githubusercontent.com/83868746/356563980-9390de10-4db9-42e9-b539-4143dc2e2522.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQzOTc0MjksIm5iZiI6MTcyNDM5NzEyOSwicGF0aCI6Ii84Mzg2ODc0Ni8zNTY1NjM5ODAtOTM5MGRlMTAtNGRiOS00MmU5LWI1MzktNDE0M2RjMmUyNTIyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIzVDA3MTIwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ5ZDhmMTZkMDNkZWRhYjRhMDBmOWI4NDVjZjQ0ZmJkNWUxNGJlZDI4MDc1N2UzNGNlZTUxYTVhZGMzOTQ0YWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.K2UCsGtkQqHUMm9lTzA0TpB7s9LErLfyQYTMiAwxAxM) Hi,i want to know if the pretrain dataset of pointbert is shapenet
> 
> According to the pointbert paper, the pre-training dataset is shapenet, so what's the consequence?
ohh i just want to follow the setting.thanks for your clear reply !
